### ISSUE TITLE
Request to add SSL keys upload to SDK

### ISSUE THREAD

**Issue by james-hastings** [alertlogic/alertlogic-sdk-definitions#276]
Requesting functionality to add SSL certs to Alert Logic UI via SDK.  Would greatly simplify upload for users.

**Comment by anton-b** [comment]
@james-hastings https://github.com/alertlogic/alertlogic-sdk-definitions/blob/master/alsdkdefs/apis/credentials/credentials.v2.yaml#L77

**Comment by motobob** [comment]
please re-open if request is still not satisfied.

cc @carlisom
